FROM nginx:1.25.3-alpine

# Copy NGINX configuration
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# Define a static volume for NGINX
VOLUME /app/backend/staticfiles

# Expose port 80
EXPOSE 80