# Generated by Django 5.0.2 on 2024-02-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardstatus',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='cardstatus',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cardstatus',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cardstatus',
            name='card_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cardstatus',
            name='user_mobile',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='cardstatus',
            index=models.Index(fields=['card_id', 'user_mobile'], name='card_status_card_id_4456cc_idx'),
        ),
        migrations.AlterModelTable(
            name='cardstatus',
            table='card_status',
        ),
    ]
