# Generated by Django 5.0.2 on 2024-02-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_status', '0002_alter_cardstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardstatus',
            name='user_mobile',
            field=models.CharField(max_length=255),
        ),
    ]
